development:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: quran_db
  encoding: utf8
  username: quran
  password: crackme

test:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: quran_db
  encoding: utf8
  username: quran
  password: crackme

production:
  adapter: mysql
  socket: /var/run/mysqld/mysqld.sock
  database: quran_db
  encoding: utf8
  username: quran
  password: crackme
